# Generated by Django 4.2.3 on 2023-09-01 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_usermodel_editor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='editor',
            field=models.BooleanField(default=False),
        ),
    ]
